name: Ninsar CI

on:
  push:
    branches: [main]
    tags-ignore: ["v*"]
  pull_request:
    branches: [main]
  create:
    tags: ["v*"]
    branches: [main]

jobs:

  build:
    if: github.ref != 'refs/heads/main' # To run only on PRs & Tags
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            platfom: Android
            unity-version: 2020.3.15f1

          - os: macos-latest
            platfom: iOS
    
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: 'recursive'

      - name: Cache Library & other Unity trash
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.platform }}
          unityVersion: ${{ matrix.unity-version }}
          buildsPath: Builds
          versioning: Tag

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{matrix.platform}}
          path: Build/${{matrix.platform}}
  
  # release:
  #   if: github.event == 'create'
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download builds
  #       uses: actions/download-artifact@v2
  #       with:
  #         path: Builds/
      
  #     - name: Create release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         generate_release_notes: true
  #         files: Builds/*

  # publish:
  #   if: github.event == 'create'
  #   needs: build
  #   runs-on: ubuntu-latest