name: Ninsar CI

on:
  push:
    branches: [main]
    tags-ignore: ["v*"]
  pull_request:
    branches: [main]
  create:
    tags: ["v*"]
    branches: [main]

jobs:

  build:
    if: github.ref != 'refs/heads/main' # To run only on PRs & Tags
    strategy:
      fail-fast: true
      matrix:
        unity-version: [2020.3.15f1]
        platform: [Android, iOS]
        sign: [false]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: 'recursive'

      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ github.event.repository.name }}-${{ matrix.unity-version }}-${{ matrix.platform }}

      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.platform }}
          unityVersion: ${{ matrix.unity-version }}
          buildsPath: Builds
          versioning: Tag
          androidAppBundle: false
          androidKeystoreName: ${{ matrix.sign && 'user.keystore' || '' }}
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

      # - name: Build Xcode project if iOS

      - name: Build Android as .aab if release
        if: matrix.platform == 'Android' && github.event == 'create'
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.platform }}
          unityVersion: ${{ matrix.unity-version }}
          buildsPath: Builds
          versioning: Tag
          androidAppBundle: true
          androidKeystoreName: ${{ matrix.sign && 'user.keystore' || '' }}
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{matrix.platform}}
          path: Builds/${{matrix.platform}}
  
  # release:
  #   if: github.event == 'create'
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download builds
  #       uses: actions/download-artifact@v2
  #       with:
  #         path: Builds/
      
  #     - name: Create release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         generate_release_notes: true
  #         files: Builds/*

  # publish:
  #   if: github.event == 'create'
  #   needs: build
  #   runs-on: ubuntu-latest